# Generated by Django 6.0.2 on 2026-02-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CitySearch',
        ),
    ]
